# Generated by Django 5.1.7 on 2025-03-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("license_number", models.CharField(max_length=20, unique=True)),
                ("license_status", models.CharField(default="active", max_length=20)),
                ("violation_history", models.TextField(blank=True, null=True)),
                (
                    "penalties",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("face_embedding", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
