# Generated by Django 5.2 on 2025-05-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='violation_type',
        ),
        migrations.AddField(
            model_name='violation',
            name='violation_type',
            field=models.ManyToManyField(related_name='violations', to='driver_api.violationtype'),
        ),
    ]
